#while True:
    #    print("Sound level: " + input.sound_level())
#    if input.sound_level() > 150:
    #        light.show_animation(light.rainbowAnimation, 500)
#    else:
    #        light.clear()


#while True:
    #    if input.light_level() > 8:
        #        music.ba_ding.play_until_done()

#music.set_volume(20)
#music.play_melody("C C G G A A G F F E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
#light.show_animation(light.rainbowAnimation, 500)

music.set_volume(20)
music.play_melody("C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G ", 150)
light.show_animation(light.rainbowAnimation, 500)
music.play_melody("C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("A ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("A  ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G F F E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("F F E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("F E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("F F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("F E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("E E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("E D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("D C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("C C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("C G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("A A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("A G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("G F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("F F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("F E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("E E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("E D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("D D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("D C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()
music.play_melody("C ", 150)
light.show_animation(light.rainbowAnimation, 500)
light.clear()

