// while True:
//     print("Sound level: " + input.sound_level())
//     if input.sound_level() > 150:
//         light.show_animation(light.rainbowAnimation, 500)
//     else:
//         light.clear()
// while True:
//     if input.light_level() > 8:
//         music.ba_ding.play_until_done()
// music.set_volume(20)
// music.play_melody("C C G G A A G F F E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
// light.show_animation(light.rainbowAnimation, 500)
music.setVolume(20)
music.playMelody("C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G ", 150)
light.showAnimation(light.rainbowAnimation, 500)
music.playMelody("C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("A ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("A  ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G F F E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("F F E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("F E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("E E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("E D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("D D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("D C G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("F F E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("E E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("E D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("D G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("F F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("F E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("E E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("E D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("D C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("C C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("C G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("A A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("A G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("G F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("F F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("F E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("E E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("E D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("D D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("D C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
music.playMelody("C ", 150)
light.showAnimation(light.rainbowAnimation, 500)
light.clear()
